require 'versioncake/strategies/extraction_strategy'
require 'versioncake/strategies/http_accept_parameter_strategy'
require 'versioncake/strategies/http_header_strategy'
require 'versioncake/strategies/query_parameter_strategy'
require 'versioncake/strategies/request_parameter_strategy'
require 'versioncake/strategies/custom_strategy'

require 'versioncake/action_view/template'
require 'versioncake/action_view/versions'
require 'versioncake/action_view/lookup_context'
require 'versioncake/action_view/resolver'
require 'versioncake/action_controller/versioning'
require 'versioncake/action_view/railtie'