require 'versioncake/strategies/extraction_strategy'
require 'versioncake/strategies/http_accept_parameter_strategy'
require 'versioncake/strategies/http_header_strategy'
require 'versioncake/strategies/query_parameter_strategy'
require 'versioncake/strategies/path_parameter_strategy'
require 'versioncake/strategies/request_parameter_strategy'
require 'versioncake/strategies/custom_strategy'

require 'versioncake/exceptions'
require 'versioncake/configuration'
require 'versioncake/controller_additions'
require 'versioncake/view_additions'
require 'versioncake/versioned_request'
require 'versioncake/railtie'
require 'versioncake/cli'
